/**
 * Type definitions for the Component Catalogue view.
 *
 * Data source: model-introspection.json (generated by gen_model_introspection.py).
 * The catalogue consumes coverageMatrix entries that have a catalogueTag property,
 * plus the top-level facets and comprehension summaries.
 */

// --- Per-element types ---

export interface DomainInstance {
  name: string;
  package: string;
}

export interface CatalogueTag {
  /** e.g. { bmmConcern: "ServiceConcept", classification: "General" } */
  [dimension: string]: string;
}

export interface UserFacing {
  friendlyName: string;
  shortDescription: string;
}

export interface PurposiveDescription {
  description: string;
}

export interface ComprehensionFlags {
  surfaceEnumValues?: boolean;
  surfaceDomainInstantiations?: boolean;
  surfaceRelatedConcepts?: boolean;
  surfaceAttributes?: boolean;
}

export interface EnumValueSurface {
  enumName: string;
  attributeName: string;
  values: string[];
}

export interface DomainInstantiationSurface {
  [domain: string]: {
    count: number;
    instances: string[];
  };
}

export interface RelatedConceptSurface {
  name: string;
  friendlyName?: string;
  strength?: 'strong' | 'moderate' | 'weak' | 'contextual';
  rationale?: string;
}

export interface AttributeSurface {
  name: string;
  type: string;
}

export interface ComprehensionContent {
  flags: ComprehensionFlags;
  enumValues?: EnumValueSurface[];
  domainInstantiations?: DomainInstantiationSurface;
  relatedConcepts?: RelatedConceptSurface[];
  attributes?: AttributeSurface[];
}

export interface CatalogueElement {
  name: string;
  layer: string;
  package: string;
  doc: string;
  catalogueTag: CatalogueTag;
  userFacing?: UserFacing;
  purposiveDescription?: PurposiveDescription;
  comprehension?: ComprehensionFlags;
  /** Keyed by domain identifier (core, csw, suds, paws). */
  domains: Record<string, DomainInstance[]>;
}

// --- Facet summary types ---

export interface FacetDimension {
  values: string[];
  counts: Record<string, number>;
  total: number;
}

export type FacetSummary = Record<string, FacetDimension>;

// --- Comprehension summary ---

export interface ComprehensionSummary {
  catalogueTaggedCount: number;
  userFacingCount: number;
  purposiveDescriptionCount: number;
  comprehensionAnnotationCount: number;
  coveragePercent: number;
  purposiveCoveragePercent: number;
  missingUserFacing: Array<{ name: string; package: string }>;
  missingPurposiveDescription: Array<{ name: string; package: string }>;
}

// --- Domain metadata ---

export interface DomainMeta {
  label: string;
  description: string;
  elementCount: number;
}

// --- Top-level page data ---

export interface CataloguePageData {
  elements: CatalogueElement[];
  facets: FacetSummary;
  comprehension: ComprehensionSummary;
  domains: Record<string, DomainMeta>;
  generatedAt: string;
  generator: string;
}

// --- Grouping types ---

export type GroupingAxis =
  | 'bmmConcern'
  | 'classification'
  | 'package'
  | 'domainCoverage'
  | string; // future facet dimensions appear dynamically

export interface GroupingOption {
  key: GroupingAxis;
  label: string;
}
