/**
 * Type definitions for the Governance Traceability view.
 *
 * Data source: model-introspection.json → governanceTraceability section
 * (generated by gen_model_introspection.py, Phase 6).
 */

// --- Requirement def (meta model level) ---

export interface GovernanceRequirementDef {
  name: string;
  package: string;
  layer: string;
  doc: string;
  attributes: Array<{ name: string; type?: string; value?: string }>;
  catalogueTag: Record<string, string>;
  userFacing?: { friendlyName: string; shortDescription: string };
}

// --- Constraint def (domain-specific) ---

export interface GovernanceConstraintDef {
  name: string;
  package: string;
  sourceDomain: string;
  doc: string;
  attributes: Array<{ name: string; type?: string }>;
}

// --- Satisfy chain ---

export interface SatisfyChain {
  satisfyName: string;
  requirementDef: string;
  constraintUsage: string;
  constraintDef: string;
  sourceDomain: string;
  package: string;
}

// --- Requirement instance (domain-level usage) ---

export interface GovernanceRequirementInstance {
  name: string;
  typedBy: string;
  sourceDomain: string;
  package: string;
  doc: string;
  attributes: Array<{ name: string; value?: string; type?: string; isRedefinition?: boolean }>;
}

// --- Audit evidence instance ---

export interface AuditEvidenceInstance {
  name: string;
  typedBy: string;
  sourceDomain: string;
  package: string;
  doc: string;
  attributes: Array<{ name: string; value?: string; type?: string; isRedefinition?: boolean }>;
}

// --- Top-level governance traceability data ---

export interface GovernanceTraceability {
  requirementDefs: GovernanceRequirementDef[];
  constraintDefs: GovernanceConstraintDef[];
  satisfyChains: SatisfyChain[];
  requirementInstances: GovernanceRequirementInstance[];
  auditEvidenceInstances: AuditEvidenceInstance[];
}

// --- Page data ---

export interface GovernancePageData {
  governance: GovernanceTraceability;
  domains: Record<string, { label: string; description: string; elementCount: number }>;
  generatedAt: string;
}
