/**
 * Type definitions for the Ontology Hierarchy view.
 *
 * Data source: model-introspection.json → ontologicalHierarchy
 * Generated by gen_model_introspection.py (build_ontological_hierarchy).
 */

export type HierarchyTier = 'bfo' | 'midLevel' | 'bmm';

export interface HierarchyNode {
  name: string;
  tier: HierarchyTier;
  children?: HierarchyNode[];
  /** Only on midLevel nodes */
  prefix?: string;
  className?: string;
  /** Only on bmm nodes */
  package?: string;
  friendlyName?: string;
  bmmConcern?: string;
}

export interface HierarchyStats {
  bmmElementCount: number;
  bfoClassesUsed: string[];
  midLevelClassesUsed: string[];
  unmappedMidLevel: string[];
}

export interface OntologicalHierarchy {
  tree: HierarchyNode;
  stats: HierarchyStats;
}

export interface OntologyPageData {
  hierarchy: OntologicalHierarchy;
  generatedAt: string;
  generator: string;
}
