/**
 * Type definitions for the Ontology Hierarchy view.
 *
 * Data source: model-introspection.json → ontologicalHierarchy
 * Generated by gen_model_introspection.py (build_ontological_hierarchy).
 */

export type HierarchyTier = 'bfo' | 'midLevel' | 'bmm';

export interface HierarchyNode {
  name: string;
  tier: HierarchyTier;
  children?: HierarchyNode[];
  /** Only on midLevel nodes */
  prefix?: string;
  className?: string;
  /** Only on bmm nodes */
  package?: string;
  friendlyName?: string;
  bmmConcern?: string;
}

export interface HierarchyStats {
  bmmElementCount: number;
  bfoClassesUsed: string[];
  midLevelClassesUsed: string[];
  unmappedMidLevel: string[];
}

export interface OntologicalHierarchy {
  tree: HierarchyNode;
  stats: HierarchyStats;
}

export interface OntologyPageData {
  hierarchy: OntologicalHierarchy;
  generatedAt: string;
  generator: string;
}

// --- Reasoning summary types ---

export interface OntologyFileEntry {
  name: string;
  file: string;
  sizeBytes: number;
  present: boolean;
}

export interface ObjectProperty {
  name: string;
  label: string;
  domain: string;
  range: string;
  functional: boolean;
  comment: string;
}

export interface ReasoningStats {
  ontologyFileCount: number;
  objectPropertyCount: number;
  reifiedWeightCount: number;
  domainClassCount: number;
  axiomFilePresent: boolean;
  /** Added Phase 4 (Session 158) */
  namedIndividualCount?: number;
  datatypePropertyCount?: number;
  sparqlQueryCount?: number;
}

export interface ViolationTest {
  ran: boolean;
  passed: boolean | null;
}

// --- Reasoning vocabulary types (Phase 4, Session 158) ---

export interface ReasoningClass {
  iri: string;
  label: string;
  comment: string;
  parents: string[];
  /** Functional grouping for display: foundation, core, evidence, probabilistic, constraints, knowledge, safety */
  module: string;
}

export interface ReasoningNamedIndividual {
  iri: string;
  label: string;
  types: string[];
}

export interface ReasoningDatatypeProperty {
  iri: string;
  label: string;
  domain: string;
  range: string;
  comment: string;
}

export interface CrossModuleAxiom {
  subject: string;
  predicate: string;
  object: string;
  description: string;
}

export interface ReasoningModuleSummary {
  classCount: number;
  objectPropertyCount: number;
  datatypePropertyCount: number;
  namedIndividualCount: number;
}

export interface ReasoningVocabulary {
  classes: ReasoningClass[];
  namedIndividuals: ReasoningNamedIndividual[];
  objectProperties: ObjectProperty[];
  datatypeProperties: ReasoningDatatypeProperty[];
  crossModuleAxioms: CrossModuleAxiom[];
  moduleSummary: ReasoningModuleSummary;
}

export interface ReasoningSummary {
  generatedAt: string;
  generator: string;
  reasoner: string;
  consistent: boolean;
  unsatisfiableClasses: string[];
  ontologyStack: OntologyFileEntry[];
  objectProperties: ObjectProperty[];
  stats: ReasoningStats;
  violationTest: ViolationTest;
  /** Added Phase 4 (Session 158) — reasoning vocabulary structure */
  reasoningVocabulary?: ReasoningVocabulary;
}
