/**
 * Type definitions for the Ontology Hierarchy view.
 *
 * Data source: model-introspection.json → ontologicalHierarchy
 * Generated by gen_model_introspection.py (build_ontological_hierarchy).
 */

export type HierarchyTier = 'bfo' | 'midLevel' | 'bmm';

export interface HierarchyNode {
  name: string;
  tier: HierarchyTier;
  children?: HierarchyNode[];
  /** Only on midLevel nodes */
  prefix?: string;
  className?: string;
  /** Only on bmm nodes */
  package?: string;
  friendlyName?: string;
  bmmConcern?: string;
}

export interface HierarchyStats {
  bmmElementCount: number;
  bfoClassesUsed: string[];
  midLevelClassesUsed: string[];
  unmappedMidLevel: string[];
}

export interface OntologicalHierarchy {
  tree: HierarchyNode;
  stats: HierarchyStats;
}

export interface OntologyPageData {
  hierarchy: OntologicalHierarchy;
  generatedAt: string;
  generator: string;
}

// --- Reasoning summary types ---

export interface OntologyFileEntry {
  name: string;
  file: string;
  sizeBytes: number;
  present: boolean;
}

export interface ObjectProperty {
  name: string;
  label: string;
  domain: string;
  range: string;
  functional: boolean;
  comment: string;
}

export interface ReasoningStats {
  ontologyFileCount: number;
  objectPropertyCount: number;
  reifiedWeightCount: number;
  domainClassCount: number;
  axiomFilePresent: boolean;
}

export interface ViolationTest {
  ran: boolean;
  passed: boolean | null;
}

export interface ReasoningSummary {
  generatedAt: string;
  generator: string;
  reasoner: string;
  consistent: boolean;
  unsatisfiableClasses: string[];
  ontologyStack: OntologyFileEntry[];
  objectProperties: ObjectProperty[];
  stats: ReasoningStats;
  violationTest: ViolationTest;
}
